routes:
- name: Kuala Lumpur to Batam
  origin: KUL
  destination: BTH
  departure_date: '2026-09-24'
  return_date: '2026-09-27'
  target_price: 350.0
  currency: myr
- name: New York to Tokyo
  origin: NYC
  destination: TYO
  departure_date: '2026-07-06'
  return_date: '2026-07-31'
  target_price: 6888.0
  currency: usd
