routes:
- name: Kuala Lumpur to Batam
  origin: KUL
  destination: BTH
  departure_date: '2026-09-24'
  return_date: '2026-09-27'
  target_price: 350.0
  currency: myr
- name: Kuala Lumpur to Guangzhou
  origin: KUL
  destination: CAN
  departure_date: '2026-09-16'
  return_date: '2026-09-20'
  target_price: 1988.0
  currency: myr
- name: New York to Tokyo
  origin: NYC
  destination: TYO
  departure_date: '2026-07-13'
  return_date: '2026-07-31'
  target_price: 6650.0
  currency: usd
- name: Kuala Lumpur to Tokyo
  origin: KUL
  destination: TYO
  departure_date: '2026-07-27'
  return_date: '2026-08-08'
  target_price: 2650.0
  currency: myr
